export enum UserStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  UNSPECIFIED = 'UNSPECIFIED',
}

export enum DosageForm {
  TABLET = 'TABLET',
  CAPSULE = 'CAPSULE',
  SYRUP = 'SYRUP',
  SUSPENSION = 'SUSPENSION',
  INJECTION = 'INJECTION',
  CREAM = 'CREAM',
  OINTMENT = 'OINTMENT',
  DROPS = 'DROPS',
  INHALER = 'INHALER',
  POWDER = 'POWDER',
  OTHER = 'OTHER',
}

export enum ReceiptStatus {
  DRAFT = 'DRAFT',
  POSTED = 'POSTED',
  CANCELLED = 'CANCELLED',
}

export enum SupplyRequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  PARTIALLY_FULFILLED = 'PARTIALLY_FULFILLED',
  FULFILLED = 'FULFILLED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum TransferStatus {
  DRAFT = 'DRAFT',
  PREPARED = 'PREPARED',
  IN_TRANSIT = 'IN_TRANSIT',
  SHIPPED = 'SHIPPED',
  RECEIVED = 'RECEIVED',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  CANCELLED = 'CANCELLED',
}

export enum DispensingStatus {
  DRAFT = 'DRAFT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MovementType {
  RECEIPT = 'RECEIPT',
  TRANSFER_OUT = 'TRANSFER_OUT',
  TRANSFER_IN = 'TRANSFER_IN',
  DISPENSE = 'DISPENSE',
  RETURN = 'RETURN',
  ADJUSTMENT_IN = 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT = 'ADJUSTMENT_OUT',
  DAMAGE = 'DAMAGE',
  EXPIRED = 'EXPIRED',
}

export enum MovementReferenceType {
  STOCK_RECEIPT = 'STOCK_RECEIPT',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  DISPENSING_RECORD = 'DISPENSING_RECORD',
  SUPPLY_REQUEST = 'SUPPLY_REQUEST',
  ADJUSTMENT = 'ADJUSTMENT',
  DAMAGE = 'DAMAGE',
  EXPIRY = 'EXPIRY',
}

export enum LocationType {
  WAREHOUSE = 'WAREHOUSE',
  PHARMACY = 'PHARMACY',
}

export enum NotificationType {
  LOW_STOCK = 'LOW_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  EXPIRY_WARNING = 'EXPIRY_WARNING',
  EXPIRED_BATCH = 'EXPIRED_BATCH',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED_STOCK = 'EXPIRED_STOCK',
  SUPPLY_REQUEST = 'SUPPLY_REQUEST',
  SUPPLY_REQUEST_SUBMITTED = 'SUPPLY_REQUEST_SUBMITTED',
  SUPPLY_REQUEST_APPROVED = 'SUPPLY_REQUEST_APPROVED',
  SUPPLY_REQUEST_REJECTED = 'SUPPLY_REQUEST_REJECTED',
  PENDING_SUPPLY_REQUEST = 'PENDING_SUPPLY_REQUEST',
  TRANSFER = 'TRANSFER',
  TRANSFER_CREATED = 'TRANSFER_CREATED',
  TRANSFER_RECEIVED = 'TRANSFER_RECEIVED',
  TRANSFER_AWAITING_RECEIPT = 'TRANSFER_AWAITING_RECEIPT',
  SYSTEM = 'SYSTEM',
}

export enum NotificationSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum NotificationStatus {
  UNREAD = 'UNREAD',
  READ = 'READ',
  ARCHIVED = 'ARCHIVED',
}

export enum AuditAction {
  CREATE_MEDICINE = 'CREATE_MEDICINE',
  UPDATE_MEDICINE = 'UPDATE_MEDICINE',
  DEACTIVATE_MEDICINE = 'DEACTIVATE_MEDICINE',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DEACTIVATE_CATEGORY = 'DEACTIVATE_CATEGORY',
  CREATE_UNIT = 'CREATE_UNIT',
  UPDATE_UNIT = 'UPDATE_UNIT',
  DEACTIVATE_UNIT = 'DEACTIVATE_UNIT',
  CREATE_BATCH = 'CREATE_BATCH',
  UPDATE_BATCH = 'UPDATE_BATCH',
  CREATE_RECEIPT = 'CREATE_RECEIPT',
  POST_RECEIPT = 'POST_RECEIPT',
  CANCEL_RECEIPT = 'CANCEL_RECEIPT',
  CREATE_SUPPLY_REQUEST = 'CREATE_SUPPLY_REQUEST',
  SUBMIT_SUPPLY_REQUEST = 'SUBMIT_SUPPLY_REQUEST',
  APPROVE_SUPPLY_REQUEST = 'APPROVE_SUPPLY_REQUEST',
  REJECT_SUPPLY_REQUEST = 'REJECT_SUPPLY_REQUEST',
  CANCEL_SUPPLY_REQUEST = 'CANCEL_SUPPLY_REQUEST',
  CREATE_TRANSFER = 'CREATE_TRANSFER',
  PREPARE_TRANSFER = 'PREPARE_TRANSFER',
  SHIP_TRANSFER = 'SHIP_TRANSFER',
  RECEIVE_TRANSFER = 'RECEIVE_TRANSFER',
  CANCEL_TRANSFER = 'CANCEL_TRANSFER',
  DISPENSE_MEDICINE = 'DISPENSE_MEDICINE',
  CREATE_DISPENSING = 'CREATE_DISPENSING',
  COMPLETE_DISPENSING = 'COMPLETE_DISPENSING',
  CREATE_BENEFICIARY = 'CREATE_BENEFICIARY',
  UPDATE_BENEFICIARY = 'UPDATE_BENEFICIARY',
  ACTIVATE_BENEFICIARY = 'ACTIVATE_BENEFICIARY',
  DEACTIVATE_BENEFICIARY = 'DEACTIVATE_BENEFICIARY',
  EXPORT_REPORT = 'EXPORT_REPORT',
  RUN_ALERT_EVALUATION = 'RUN_ALERT_EVALUATION',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  MARK_DAMAGED = 'MARK_DAMAGED',
  MARK_EXPIRED = 'MARK_EXPIRED',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  CREATE_PHARMACY = 'CREATE_PHARMACY',
  UPDATE_PHARMACY = 'UPDATE_PHARMACY',
  CREATE_WAREHOUSE = 'CREATE_WAREHOUSE',
  UPDATE_WAREHOUSE = 'UPDATE_WAREHOUSE',
  INVITE_USER = 'INVITE_USER',
  ACCEPT_INVITATION = 'ACCEPT_INVITATION',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
  SEND_TEST_EMAIL = 'SEND_TEST_EMAIL',
  UPDATE_NOTIFICATION_PREFERENCES = 'UPDATE_NOTIFICATION_PREFERENCES',
  IMPORT_CATEGORIES = 'IMPORT_CATEGORIES',
  IMPORT_MEDICINES = 'IMPORT_MEDICINES',
  PURGE_DATA = 'PURGE_DATA',
}

export enum RoleCode {
  SUPER_ADMIN = 'SUPER_ADMIN',
  WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER',
  WAREHOUSE_STAFF = 'WAREHOUSE_STAFF',
  PHARMACY_MANAGER = 'PHARMACY_MANAGER',
  PHARMACY_STAFF = 'PHARMACY_STAFF',
  REPORT_VIEWER = 'REPORT_VIEWER',
}
