import type { AuthenticatedUser } from '@mh/shared';

const ALIASES: Record<string, string[]> = {
  'dashboard:view': ['dashboard:admin', 'dashboard:warehouse', 'dashboard:pharmacy'],
  'report:view': ['reports:warehouse', 'reports:pharmacy', 'reports:dispensing'],
  'users:read': ['user:view'],
  'roles:read': ['role:view'],
  'pharmacies:read': ['pharmacy:view'],
  'warehouse-stock:read': ['warehouse-stock:view'],
  'warehouse-stock:view': ['warehouse-stock:read'],
  'warehouse-stock:adjust': ['warehouse-stock:manage'],
  'stock:damage': [],
  'stock:expire': [],
  'receipts:read': ['receipt:view'],
  'receipt:view': ['receipts:read'],
  'receipts:create': ['receipt:create'],
  'receipt:create': ['receipts:create'],
  'receipts:post': ['receipt:post'],
  'receipt:post': ['receipts:post'],
  'receipt:cancel': [],
  'stock-movements:read': ['stock-movement:view'],
  'stock-movement:view': ['stock-movements:read'],
  'pharmacy-stock:read': ['pharmacy-stock:view'],
  'pharmacy-stock:view': ['pharmacy-stock:read'],
  'supply-requests:read': ['supply-request:view'],
  'supply-request:view': ['supply-requests:read'],
  'supply-requests:create': ['supply-request:create'],
  'supply-request:create': ['supply-requests:create'],
  'supply-request:edit': ['supply-requests:create', 'supply-request:create'],
  'supply-requests:submit': ['supply-request:submit'],
  'supply-request:submit': ['supply-requests:submit'],
  'supply-requests:approve': ['supply-request:approve'],
  'supply-request:approve': ['supply-requests:approve'],
  'supply-requests:reject': ['supply-request:reject'],
  'supply-request:reject': ['supply-requests:reject'],
  'supply-requests:cancel': ['supply-request:cancel'],
  'supply-request:cancel': ['supply-requests:cancel'],
  'transfers:read': ['transfer:view'],
  'transfer:view': ['transfers:read'],
  'transfers:create': ['transfer:create'],
  'transfer:create': ['transfers:create'],
  'transfer:edit': ['transfers:create', 'transfer:create'],
  'transfers:prepare': ['transfer:prepare'],
  'transfer:prepare': ['transfers:prepare'],
  'transfers:dispatch': ['transfer:ship'],
  'transfer:ship': ['transfers:dispatch'],
  'transfers:receive': ['transfer:receive'],
  'transfer:receive': ['transfers:receive'],
  'transfer:cancel': [],
  'notifications:read': ['notification:view'],
  'notification:view': ['notifications:read'],
  'beneficiaries:create': ['beneficiary:create'],
  'beneficiary:create': ['beneficiaries:create'],
  'medicines:read': ['medicine:view'],
  'medicine:view': ['medicines:read'],
  'medicines:create': ['medicine:create'],
  'medicine:create': ['medicines:create'],
  'medicines:update': ['medicine:update'],
  'medicine:update': ['medicines:update'],
  'categories:read': ['category:view'],
  'category:view': ['categories:read'],
  'categories:create': ['category:create', 'category:manage'],
  'category:create': ['categories:create', 'category:manage'],
  'categories:update': ['category:update', 'category:manage'],
  'category:update': ['categories:update', 'category:manage'],
  'units:read': ['unit:view'],
  'unit:view': ['units:read'],
  'units:create': ['unit:create', 'unit:manage'],
  'unit:create': ['units:create', 'unit:manage'],
  'units:update': ['unit:update', 'unit:manage'],
  'unit:update': ['units:update', 'unit:manage'],
  'batches:read': ['batch:view'],
  'batch:view': ['batches:read'],
  'batches:create': ['batch:create', 'batch:manage'],
  'batch:create': ['batches:create', 'batch:manage'],
  'batches:update': ['batch:update', 'batch:manage'],
  'batch:update': ['batches:update', 'batch:manage'],
};

export function hasPermission(user: AuthenticatedUser | null, permission: string) {
  if (!user) return false;
  if (user.roles?.includes('SUPER_ADMIN' as AuthenticatedUser['roles'][number])) return true;
  if (user.permissions.includes(permission as never)) return true;
  return (ALIASES[permission] ?? []).some((code) => user.permissions.includes(code as never));
}
